//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KhalidFoodTruck
{
    using System;
    using System.Collections.Generic;
    
    public partial class FoodTruckLocation
    {
        public int FoodTruckLocationID { get; set; }
        public string FoodTruckLocationDay { get; set; }
        public int LocationID { get; set; }
        public int FoodTruckID { get; set; }
    
        public virtual Location Location { get; set; }
        public virtual FoodTruck FoodTruck { get; set; }
    }
}
