//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KhalidFoodTruck
{
    using System;
    using System.Collections.Generic;
    
    public partial class FoodTruck
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FoodTruck()
        {
            this.FoodTruckLocations = new HashSet<FoodTruckLocation>();
        }
    
        public int FoodTruckID { get; set; }
        public string FoodTruckName { get; set; }
        public string FoodTruckPlateNumber { get; set; }
        public int FoodTypeID { get; set; }
    
        public virtual FoodType FoodType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FoodTruckLocation> FoodTruckLocations { get; set; }
    }
}
